// Code generated by paramgen. DO NOT EDIT.
// Source: github.com/conduitio/conduit-connector-sdk/cmd/paramgen

package ais

import (
	sdk "github.com/conduitio/conduit-connector-sdk"
)

func (SourceConfig) Parameters() map[string]sdk.Parameter {
	return map[string]sdk.Parameter{
		"apiUrl": {
			Default:     "https://api.spire.com/graphql",
			Description: "apiUrl is the Spire API URL to use for accessing the Spire GraphQL API.",
			Type:        sdk.ParameterTypeString,
			Validations: []sdk.Validation{},
		},
		"batchSize": {
			Default:     "100",
			Description: "batchSize is the quantity of vessels to retrieve per API call.",
			Type:        sdk.ParameterTypeInt,
			Validations: []sdk.Validation{
				sdk.ValidationRequired{},
			},
		},
		"query": {
			Default:     "",
			Description: "query is the GraphQL query to use when pulling data from the Spire API.",
			Type:        sdk.ParameterTypeString,
			Validations: []sdk.Validation{},
		},
		"token": {
			Default:     "",
			Description: "token is the access token to use when accessing the Spire GraphQL API.",
			Type:        sdk.ParameterTypeString,
			Validations: []sdk.Validation{
				sdk.ValidationRequired{},
			},
		},
	}
}
