// Code generated by paramgen. DO NOT EDIT.
// Source: github.com/ConduitIO/conduit-commons/tree/main/paramgen

package ais

import (
	"github.com/conduitio/conduit-commons/config"
)

const (
	SourceConfigApiUrl    = "apiUrl"
	SourceConfigBatchSize = "batchSize"
	SourceConfigQuery     = "query"
	SourceConfigToken     = "token"
)

func (SourceConfig) Parameters() map[string]config.Parameter {
	return map[string]config.Parameter{
		SourceConfigApiUrl: {
			Default:     "https://api.spire.com/graphql",
			Description: "APIURL is the Spire API URL to use for accessing the Spire GraphQL API.",
			Type:        config.ParameterTypeString,
			Validations: []config.Validation{},
		},
		SourceConfigBatchSize: {
			Default:     "100",
			Description: "batchSize is the quantity of vessels to retrieve per Spire GraphQL API call.",
			Type:        config.ParameterTypeInt,
			Validations: []config.Validation{},
		},
		SourceConfigQuery: {
			Default:     "",
			Description: "Query is the GraphQL Query to use when pulling data from the Spire API.",
			Type:        config.ParameterTypeString,
			Validations: []config.Validation{},
		},
		SourceConfigToken: {
			Default:     "",
			Description: "Token is the access token to use when accessing the Spire GraphQL API.",
			Type:        config.ParameterTypeString,
			Validations: []config.Validation{
				config.ValidationRequired{},
			},
		},
	}
}
